pool:
  vmImage: ubuntu-latest
  name: Azure Pipelines
  demands: java

trigger:
  branches:
    include:
      - dev
      - version-5
      - 6.0.0
      - 7.0.0
    exclude:
      - '*'

variables:
  buildConfiguration: 'Release'
  prPipeline: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloud-ADT'
    organization: typinghard
    projectKey: 'typinghard_azure-devops-tracker'
    extraProperties: |
     sonar.exclusions=**/obj/**,**/*.dll
     sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
     sonar.cs.vscoveragexml.reportsPaths=**/coverage.opencover.xml
     sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
- task: CmdLine@2
  inputs:
    script: dotnet test --configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --collect "Code Coverage" /p:Exclude=[xunit.*]*
  displayName: 'Run Tests'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'