<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>AzureDevOpsTracker</PackageId>
    <Authors>Elvis Souza | Diego Galante</Authors>
    <Company>TypingHard</Company>
    <Product>Azure DevOps Tracker</Product>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/typinghard/azure-devops-tracker</PackageProjectUrl>
    <RepositoryUrl>https://github.com/typinghard/azure-devops-tracker</RepositoryUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageIcon>adt_icon.png</PackageIcon>
    <PackageIconUrl />
    <RepositoryType>GitHub</RepositoryType>
    <PackageTags>Azure DevOps Tracker Columns State Tracking Track Board Scrum Kanbam Time Column Timing Workitem Worked Hours Team Performance</PackageTags>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseFile>LICENSE.md.txt</PackageLicenseFile>
    <Description>A NuGet that allows you to use a Azure DevOps Service Hook to track workitems changes in a simply and detailed way.</Description>
    <AssemblyVersion>8.0.0.0</AssemblyVersion>
    <FileVersion>8.0.3</FileVersion>
    <Version>8.0.3</Version>
    <PackageReleaseNotes></PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../LICENSE.md.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>

	<None Include="README.md" Pack="true" PackagePath="\"/>

  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="adt_icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
